# Generated by Django 6.0.1 on 2026-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue'),
        ),
    ]
