# Generated by Django 6.0.1 on 2026-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_date_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_depart_camions',
            field=models.DateField(blank=True, null=True, verbose_name='Date de départ des camions'),
        ),
    ]
