# Generated by Django 6.0.1 on 2026-02-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_utilisateur_actif'),
        ('commandes', '0004_remove_commande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeSupprimee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro de commande')),
                ('date_commande', models.DateTimeField(verbose_name='Date de commande')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('date_depart_camions', models.DateField(blank=True, null=True, verbose_name='Date de départ des camions')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total HT')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('lignes_json', models.JSONField(default=list, verbose_name='Lignes de commande')),
                ('date_suppression', models.DateTimeField(auto_now_add=True, verbose_name='Date de suppression')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_supprimees', to='clients.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande supprimée',
                'verbose_name_plural': 'Commandes supprimées',
                'ordering': ['-date_suppression'],
            },
        ),
    ]
