# Generated by Django 6.0.1 on 2026-02-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_commandesupprimee'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro de commande')),
                ('nom_client', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('code_tiers', models.CharField(max_length=50, verbose_name='Code tiers')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total HT')),
                ('date_suppression_definitive', models.DateTimeField(auto_now_add=True, verbose_name='Date de suppression définitive')),
            ],
            options={
                'verbose_name': 'Historique de suppression',
                'verbose_name_plural': 'Historiques de suppression',
                'ordering': ['-date_suppression_definitive'],
            },
        ),
    ]
