# Generated by Django 6.0.1 on 2026-01-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeMotDePasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('traitee', models.BooleanField(default=False, verbose_name='Traitée')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_mdp', to='clients.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de mot de passe',
                'verbose_name_plural': 'Demandes de mot de passe',
                'ordering': ['-date_demande'],
            },
        ),
    ]
