# Generated by Django 6.0.1 on 2026-02-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_utilisateur_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueSuppressionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name="Nom d'utilisateur")),
                ('nom_client', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('code_tiers', models.CharField(max_length=50, verbose_name='Code tiers')),
                ('nb_commandes', models.PositiveIntegerField(default=0, verbose_name='Nombre de commandes')),
                ('date_suppression_definitive', models.DateTimeField(auto_now_add=True, verbose_name='Date de suppression définitive')),
            ],
            options={
                'verbose_name': 'Historique de suppression utilisateur',
                'verbose_name_plural': 'Historiques de suppression utilisateurs',
                'ordering': ['-date_suppression_definitive'],
            },
        ),
        migrations.CreateModel(
            name='UtilisateurSupprime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name="Nom d'utilisateur")),
                ('password_hash', models.CharField(max_length=128, verbose_name='Mot de passe hashé')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom')),
                ('date_joined', models.DateTimeField(verbose_name="Date d'inscription")),
                ('code_tiers', models.CharField(max_length=50, verbose_name='Code tiers')),
                ('nom_client', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom du client')),
                ('commandes_json', models.JSONField(default=list, verbose_name='Commandes')),
                ('date_suppression', models.DateTimeField(auto_now_add=True, verbose_name='Date de suppression')),
            ],
            options={
                'verbose_name': 'Utilisateur supprimé',
                'verbose_name_plural': 'Utilisateurs supprimés',
                'ordering': ['-date_suppression'],
            },
        ),
    ]
