# Generated by Django 6.0.1 on 2026-02-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_token_reset_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandeMotDePasse',
        ),
    ]
