# Generated by Django 6.0.1 on 2026-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod', models.CharField(max_length=50, verbose_name='Code produit')),
            ],
            options={
                'db_table': 'catalogue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComCli',
            fields=[
                ('tiers', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code tiers')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('complement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complément')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse')),
                ('cp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('acheminement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('date_dep', models.DateField(blank=True, null=True, verbose_name='Date départ')),
                ('date_liv', models.DateField(blank=True, null=True, verbose_name='Date livraison')),
            ],
            options={
                'db_table': 'comcli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComCliLig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod', models.CharField(max_length=50, verbose_name='Code produit')),
                ('qte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantité')),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids')),
                ('colis', models.IntegerField(blank=True, null=True, verbose_name='Colis')),
                ('pu_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire base')),
                ('pu_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire net')),
                ('commentaire_prep', models.TextField(blank=True, null=True, verbose_name='Commentaire préparation')),
            ],
            options={
                'db_table': 'comclilig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('prod', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Code produit')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
            ],
            options={
                'db_table': 'prod',
                'managed': False,
            },
        ),
    ]
