# Generated by Django 6.0.1 on 2026-01-15 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_produit', models.CharField(max_length=50, verbose_name='Référence produit')),
                ('categorie', models.CharField(blank=True, default='', max_length=100, verbose_name='Catégorie')),
                ('quantite_totale', models.PositiveIntegerField(default=0, verbose_name='Quantité totale achetée')),
                ('nombre_commandes', models.PositiveIntegerField(default=0, verbose_name='Nombre de commandes')),
                ('dernier_achat', models.DateTimeField(auto_now=True, verbose_name='Dernier achat')),
                ('premier_achat', models.DateTimeField(auto_now_add=True, verbose_name='Premier achat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_achats', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Historique achat',
                'verbose_name_plural': 'Historiques achats',
                'ordering': ['-dernier_achat'],
                'unique_together': {('client', 'reference_produit')},
            },
        ),
        migrations.CreateModel(
            name='PreferenceCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('score', models.FloatField(default=0, verbose_name='Score de préférence')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date du calcul')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_categories', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Préférence catégorie',
                'verbose_name_plural': 'Préférences catégories',
                'ordering': ['-score'],
                'unique_together': {('client', 'categorie')},
            },
        ),
    ]
